### PR TITLE
Rename annotate fasta fix

### PR DESCRIPTION
**Pull request by lynnjo**
## Description

_Provide a summary of your changes including motivation and context.
If these changes fix a bug or resolves a feature request, be sure to link to that issue._

## Type of change

_What type of changes does your code introduce? Put an `x` in boxes that apply._

- [x] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated relevant documentation

## Changelog entry

_Please add a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
annotate-fastas renamed to prepare-assemblies
```

### CODE REVIEW

**Comment by tcasstevens** [comment]
There is also a reference in ./src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt And several references in ./src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt

**Comment by tcasstevens** [comment]
Also a reference to AnnotateFastas in ./src/main/kotlin/net/maizegenetics/phgv2/utils/SeqUtils.kt

**Comment by lynnjo** [comment]
Terry – what lines?  I’m not seeing this in either AlignAssemblies or AgcCompress

From: Terry ***@***.***>
Date: Thursday, March 21, 2024 at 1:49 PM
To: maize-genetics/phg_v2 ***@***.***>
Cc: Lynn Carol Johnson ***@***.***>, Assign ***@***.***>
Subject: Re: [maize-genetics/phg_v2] Rename annotate fasta fix (PR #126)

There is also a reference in ./src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt And several references in ./src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt

**Review by tcasstevens — APPROVED** [review]

**Comment by tcasstevens** [comment]
> ./src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt

line 86 in AlignAssemblies

**Comment by tcasstevens** [comment]
> ./src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt

lines 47, 55, 63, 157, and 158 in AgcCompress

**Review by zrm22 — APPROVED** [review]

**Review by pjbradbury — APPROVED** [review]

**Pull request merged**
